<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta name="robots" content="index,follow">
    <meta http-equiv="content-type" content="text/html" charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=8; IE=7; IE=9; IE=10; IE=EDGE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="author" content="Imprimil">
    <meta name="description" content="">
    <meta name="reply-to" content="">
    <meta name="theme-color" content="#222">
    <!--<link rel="shortcut icon" type="image/png" href="favicon-16.png" sizes="16x16" />
    <link rel="shortcut icon" type="image/png" href="favicon-24.png" sizes="24x24" />
    <link rel="shortcut icon" type="image/png" href="favicon-32.png" sizes="32x32" />
    <link rel="shortcut icon" type="image/png" href="favicon-48.png" sizes="48x48" />
    <link rel="shortcut icon" type="image/png" href="favicon-64.png" sizes="64x64" />
    <link rel="shortcut icon" type="image/png" href="favicon-72.png" sizes="72x72" />
    <link rel="shortcut icon" type="image/png" href="favicon-96.png" sizes="96x96" />
    <link rel="shortcut icon" type="image/png" href="favicon-114.png" sizes="114x114" />
    <link rel="shortcut icon" type="image/png" href="favicon-128.png" sizes="128x128" />
    <link rel="shortcut icon" type="image/png" href="favicon-144.png" sizes="144x144" />
    <link rel="shortcut icon" type="image/png" href="favicon-256.png" sizes="256x256" />-->
    <title>Imprimil</title>
    <link rel="stylesheet" href="styles/normalize.css" />
    <link rel="stylesheet" href="styles/_template.css" />
	<link rel="stylesheet" href="styles/_template_home.css" />
	<link rel="stylesheet" href="styles/_template_gallery.css" />
    <link rel="stylesheet" href="styles/_common.css" />
    <link rel="stylesheet" href="styles/jquery.fancybox.min.css" />
    <script type="text/javascript" src="scripts/jquery.min.js"></script>
    <script type="text/javascript" src="scripts/jquery.fancybox.min.js"></script>
    <script type="text/javascript" src="scripts/jquery.transit.min.js"></script>
    <script type="text/javascript" src="scripts/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="scripts/_template.js"></script>
</head>
<body>
    <preloader>
        <p>Carregando...</p>
    </preloader>
    <main>
        <header></header>
        <content></content>
    </main>
    <footer>
        Font generated by <a href="http://www.flaticon.com">flaticon.com</a>. <p>Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="clockwise-angled-arrows" href="http://www.freepik.com">Freepik</a></p>  
    </footer>
</body>
</html>